version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-29
    steps:
      - checkout
      - run:
        name: Calculate cache key
        command: find . -type f \( -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle.kts' \) | sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
