version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-29
    steps:
      - checkout
      - run:
          name: Run Tests
          command: ./gradlew lint test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
