version: 2.1
general:
  build_dir: /app/build
jobs:
  build:
    docker:
      - image: circleci/android:api-29
    steps:
      - checkout
      - run: ls
      - run: ./gradlew dependencies
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
